[package]
name = "zellij"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backtrace = "0.3.55"
bincode = "1.3.1"
directories-next = "2.0"
futures = "0.3.5"
ipmpsc = "0.5.0"
libc = "0.2"
nix = "0.19.1"
nom = "6.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
signal-hook = "0.1.10"
strip-ansi-escapes = "0.1.0"
structopt = "0.3"
termion = { git = "https://gitlab.com/TheLostLambda/termion.git", features = ["serde"] }
termios = "0.3"
unicode-truncate = "0.2.0"
unicode-width = "0.1.8"
vte = "0.8.0"
strum = "0.20.0"
strum_macros = "0.20.0"
lazy_static = "1.4.0"
wasmer = "1.0.0"
wasmer-wasi = "1.0.0"

[dependencies.async-std]
version = "1.3.0"
features = ["unstable"]

[dev-dependencies]
insta = "1.6.0"

[build-dependencies]
directories-next = "2.0"
structopt = "0.3"
walkdir = "2"
toml = "0.5.8"

[workspace]
members = [
    "zellij-tile",
    "default-tiles/status-bar",
    "default-tiles/strider",
]

[profile.release]
lto = true

[package.metadata.deb]
depends = "$auto"
license-file = ["LICENSE.md", "4"]
assets = [
  # TODO?
  # ["assets/man/mosaic.1", "usr/share/man/man1/mosaic.1", "644"],
  ["target/release/mosaic", "usr/bin/mosaic", "755"],
  ["GOVERNANCE.md", "usr/share/doc/mosaic/GOVERNANCE.md", "644"],
  ["README.md", "usr/share/doc/mosaic/README.md", "644"],
  ["assets/layouts/*", "usr/share/mosaic/layouts/", "644"],
  ["assets/plugins/*", "usr/share/mosaic/plugins/", "644"],
  ["assets/completions/mosaic.bash", "usr/share/bash-completion/completions/mosaic.bash", "644"],
  ["assets/completions/mosaic.fish", "usr/share/fish/vendor_completions.d/mosaic.fish", "644"],
  ["assets/completions/_mosaic", "usr/share/zsh/vendor-completions/_mosaic", "644"],
]
